### ISSUE TITLE
How to pass arguments for Qt configure in Qt build using conan recipe?

### ISSUE THREAD

**Issue by kesavan66s** [conan-io/conan-io.github.io#268]
In our normal build script, we will call <Qt source>/configure script with our customization arguments like -qtnamespace AmeQt -qt-libpng and -I %ICU_ROOT%/include. 
In conan recipe for Qt build (V6.5.5), I could not find this call to <Qt source>/configure script.
I am not sure how to achieve this in Conan and what are all the options equivalent to above call?
Please help me.

**Comment by memsharded** [comment]
Hi @kesavan66s 

This wouldn't be the correct repo to submit this ticket.

For ConanCenter recipe questions, the repo would be ``conan-center-index``, but honestly, the activity there is too high (last year this repo got 6000 Pull Requests), so often there is no time to respond all questions.

In general, Conan recipes will have ``options``, like ``with_libpng``, that you can define from your profile like ``qt/*:with_libpng=True``, in order to activate certain features. And ``icu`` is most likely a dependency that the include path will be automatically managed, so you don't need to pass the include path explicitly yourself, the recipe will manage.

**Comment by kesavan66s** [comment]
Thanks for your response. In fact we had issues with above options. I will try it in conan-center-index.
